server:
  port: 8098    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
management: 
  security: 
    enabled: false   #disabled the spring security on the management endpoints like /env,/refresh etc. 

spring:    
  application:
    name: CREDITSCORESERVICESTUB   #current service name to be used by the eureka server
 
logging:
  level:
    org:
       springframwork:
                    web: debug